---
# Source: airflow/charts/postgresql/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: airflowv2-postgresql
  labels:
    app.kubernetes.io/name: postgresql
    helm.sh/chart: postgresql-10.5.3
    app.kubernetes.io/instance: airflowv2
    app.kubernetes.io/managed-by: Helm
  namespace: airflow
type: Opaque
data:
  postgresql-password: "cG9zdGdyZXM="
