---
# Source: airflow/templates/pvc.yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: dags-data
  labels:
    app: airflow
    chart: airflow-7.16.0
    release: airflow
    heritage: Helm
spec:
  accessModes:
    - "ReadWriteMany"
  resources:
    requests:
      storage: "1Gi"
  storageClassName: "rdtuat-managed-nfs-storage"
